# Use an official Ubuntu base image
FROM ubuntu:22.04

# Set environment variables to non-interactive (this prevents prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list
RUN apt-get update

# Install Python and pip
RUN apt-get install -y python3 python3-pip

# Optionally, clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/*