---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Clickhouse
      block:
        - name: Get clickhouse distribute
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}_amd64.deb"
            mode: '644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distribute
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            mode: '644'
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}"
      with_items:
        - /home/artem/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
        - /home/artem/clickhouse-client_{{ clickhouse_version }}_amd64.deb
        - /home/artem/clickhouse-server_{{ clickhouse_version }}_amd64.deb
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Sleep for 60 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Download Vector distribute
      ansible.builtin.get_url:
        url: "https://apt.vector.dev/pool/v/ve/vector_0.40.1-1_{{ arch }}.deb"
        dest: "./vector_0.40.1-1_{{ arch }}.deb"
        mode: '644'
    - name: Install Vector distribute
      become: true
      ansible.builtin.apt:
        deb: /home/artem/vector_0.40.1-1_{{ arch }}.deb
      notify: Start vector service
      tags: install vector
    - name: Vector config
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
        mode: '644'
      tags: config vector
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install Nginx
  hosts: lighthouse
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Remove default nginx configuration
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Nginx config
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/sites-available/static-site-config
        mode: '644'
    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link
    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
  vars:
    user: "artem"

- name: Install LightHouse
  hosts: lighthouse
  become: true
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: latest
    - name: Remove default nginx site
      ansible.builtin.file:
        path: //var/www/html/index.nginx-debian.html
        state: absent
    - name: Git clone
      ansible.builtin.git:
        repo: https://github.com/VKCOM/lighthouse
        dest: /var/www/html/
  tags: instlight